-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 20:00:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `branch_id` INT NOT NULL,
  `branch_name` VARCHAR(40) NULL,
  `mgr_id` INT NULL,
  `mgr_start_date` DATE NULL,
  `branch_city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `mgr_id_idx` (`mgr_id` ASC) VISIBLE,
  CONSTRAINT `mgr_id`
    FOREIGN KEY (`mgr_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `emp_id` INT NOT NULL,
  `first_name` VARCHAR(40) NULL,
  `last_name` VARCHAR(40) NULL,
  `birth_day` DATE NULL,
  `sex` VARCHAR(1) NULL,
  `salary` INT NULL,
  `super_id` INT NULL,
  `branch_id` INT NULL,
  `full_name` VARCHAR(45) NULL,
  `yearly_income` DOUBLE NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  INDEX `super_id_idx` (`super_id` ASC) VISIBLE,
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`branch_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `super_id`
    FOREIGN KEY (`super_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL,
  `client_name` VARCHAR(40) NULL,
  `branch_id` INT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`branch_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`works_with`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`works_with` (
  `emp_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `total_sales` INT NULL,
  PRIMARY KEY (`emp_id`, `client_id`),
  INDEX `client_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch_supplier` (
  `supplier_name` VARCHAR(40) NOT NULL,
  `supply_type` VARCHAR(40) NULL,
  `branch_branch_id` INT NOT NULL,
  PRIMARY KEY (`supplier_name`, `branch_branch_id`),
  INDEX `fk_branch_supplier_branch1_idx` (`branch_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_branch_supplier_branch1`
    FOREIGN KEY (`branch_branch_id`)
    REFERENCES `mydb`.`branch` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch1` (
  `branch_id` INT NOT NULL,
  `branch_name` VARCHAR(40) NULL,
  `mgr_id` INT NULL,
  `mgr_start_date` DATE NULL,
  PRIMARY KEY (`branch_id`),
  INDEX `mgr_id_idx` (`mgr_id` ASC) VISIBLE,
  CONSTRAINT `mgr_id`
    FOREIGN KEY (`mgr_id`)
    REFERENCES `mydb`.`employee1` (`emp_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee1` (
  `emp_id` INT NOT NULL,
  `first_name` VARCHAR(40) NULL,
  `last_name` VARCHAR(40) NULL,
  `birth_day` DATE NULL,
  `sex` VARCHAR(1) NULL,
  `salary` INT NULL,
  `branch_id` INT NULL,
  `super_id` INT NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  INDEX `super_id_idx` (`super_id` ASC) VISIBLE,
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch1` (`branch_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `super_id`
    FOREIGN KEY (`super_id`)
    REFERENCES `mydb`.`employee1` (`emp_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client1` (
  `client_id` INT NOT NULL,
  `client_name` VARCHAR(40) NULL,
  `branch_id` INT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch1` (`branch_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`works_with1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`works_with1` (
  `emp_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `total_sales` INT NULL,
  PRIMARY KEY (`emp_id`, `client_id`),
  INDEX `client_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `mydb`.`employee1` (`emp_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client1` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch_suplier1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch_suplier1` (
  `supplier_name` VARCHAR(40) NOT NULL,
  `supply_typel` VARCHAR(40) NULL,
  PRIMARY KEY (`supplier_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplies1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplies1` (
  `branch_suplier_supplier_name` VARCHAR(40) NOT NULL,
  `branch_branch_id` INT NOT NULL,
  PRIMARY KEY (`branch_suplier_supplier_name`, `branch_branch_id`),
  INDEX `fk_branch_suplier_has_branch_branch1_idx` (`branch_branch_id` ASC) VISIBLE,
  INDEX `fk_branch_suplier_has_branch_branch_suplier1_idx` (`branch_suplier_supplier_name` ASC) VISIBLE,
  CONSTRAINT `fk_branch_suplier_has_branch_branch_suplier1`
    FOREIGN KEY (`branch_suplier_supplier_name`)
    REFERENCES `mydb`.`branch_suplier1` (`supplier_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_suplier_has_branch_branch1`
    FOREIGN KEY (`branch_branch_id`)
    REFERENCES `mydb`.`branch1` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
